### ISSUE TITLE
Instanciación en paredes de oveja

### ISSUE THREAD

**Issue by guillesc05** [Proyectos1-FDI-UCM/c2324-Grupo04#116]
### Descripción

Sí que se puede instanciar ovejas pegado a la pared. Lo que pasa es que se colocan encima de la cabeza del jugador. Como en el plan de pruebas pone que no se debería, lo informo.

### Pasos 

Colocarse frente a una pared y soltar la oveja.

### Captura de pantalla o vídeo
![image](https://github.com/Proyectos1-FDI-UCM/c2324-Grupo04/assets/149385650/73bfe60c-286e-480e-b7ce-a4e1565b7f86)

**Comment by Dpgo4** [comment]
No lo cambiaremos debido a que en el plan de pruebas queríamos comprobar que la oveja no se instanciase dentro de la pared, lo cual no sucede.
